# P2CE items
portal_gun_1 = "Portal Gun"
portal_gun_2 = "Upgraded Portal Gun"
potatos = "PotatOS"
weighted_cube = "Weighted Cubes"
reflection_cube = "Redirection Cubes"
spherical_cube = "Spherical Cubes"
antique_cube = "Antique Cubes"
button = "Buttons"
old_button = "Antique Buttons"
floor_button = "Floor Buttons"
old_floor_button = "Antique Floor Buttons"
cube_button = "Cube Buttons"
ball_button = "Ball Buttons"
frankenturret = "Frankenturrets"
paint = "Three Gels"
blue_gel = "Blue Gel"
orange_gel = "Orange Gel"
white_gel = "White Gel"
laser = "Lasers"
faith_plate = "Aerial Faith Plates"
funnel = "Excursion Funnels"
bridge = "Hard Light Bridges"
laser_relays = "Laser Relays"
laser_catcher = "Laser Catchers"
turrets = "Turrets"
adventure_core = "Adventure Core"
space_core = "Space Core"
fact_core = "Fact Core"

# junk items
moon_dust = "Moon Dust"
lemon = "Lemon"
slice_of_cake = "Slice of Cake"

# trap items
motion_blur_trap = "Motion Blur Trap" 
fizzle_portal_trap = "Fizzle Portal Trap" 
butter_fingers_trap = "Butter Fingers Trap" 
cube_confetti_trap = "Cube Confetti Trap" 
slippery_floor_trap = "Slippery Floor Trap"