from dataclasses import dataclass
from ..Items import blue_gel, orange_gel, white_gel, ItemTag

@dataclass
class GelData:
    object_name: str
    object_type: str
    x: float
    y: float
    z: float
    gel_item: str

map_gel_table: dict[str, list[GelData]] = {
    "sp_a3_bomb_flings": [
        GelData(object_name="paint_bomb_maker", object_type="point_template", x=-224.0, y=-64.0, z=656.0, gel_item=blue_gel),
    ],
    "sp_a3_crazy_box": [
        GelData(object_name="paint_bomb_template", object_type="point_template", x=2240.0, y=-896.0, z=656.0, gel_item=blue_gel),
        GelData(object_name="paint_drip1", object_type="info_paint_sprayer", x=1716.0, y=-1772.0, z=714.0, gel_item=blue_gel),
        GelData(object_name="paint_sprayer_bounce", object_type="info_paint_sprayer", x=1280.0, y=-1408.0, z=1776.0, gel_item=blue_gel),
    ],
    "sp_a3_end": [
        GelData(object_name="paint_trickle_blue_1", object_type="info_paint_sprayer", x=-288.0, y=640.0, z=-228.0, gel_item=blue_gel),
        GelData(object_name="paint_trickle_orange_1", object_type="info_paint_sprayer", x=-2112.0, y=-224.0, z=-2614.0, gel_item=orange_gel),
        GelData(object_name="paint_trickle_white_1", object_type="info_paint_sprayer", x=-1728.0, y=422.0, z=-2372.0, gel_item=white_gel),
        GelData(object_name="paint_trickle_blue_2", object_type="info_paint_sprayer", x=-2624.0, y=192.0, z=-2080.0, gel_item=blue_gel),
        GelData(object_name="paint_trickle_blue_2", object_type="info_paint_sprayer", x=-2224.0, y=192.0, z=-2080.0, gel_item=blue_gel),
        GelData(object_name="paint_trickle_white_2", object_type="info_paint_sprayer", x=-136.0, y=256.0, z=-1728.0, gel_item=white_gel),
        GelData(object_name="paint_duct_1", object_type="info_paint_sprayer", x=-872.0, y=359.0, z=-1088.0, gel_item=white_gel),
        GelData(object_name="paint_duct_2", object_type="info_paint_sprayer", x=-872.0, y=359.0, z=-752.0, gel_item=white_gel),
        GelData(object_name="paint_duct_3", object_type="info_paint_sprayer", x=-1306.0, y=358.0, z=-85.0, gel_item=white_gel),
        GelData(object_name="paint_duct_4", object_type="info_paint_sprayer", x=-1583.0, y=357.0, z=181.0, gel_item=white_gel),
    ],
    "sp_a3_jump_intro": [
        GelData(object_name="paint_sprayer_jump_2", object_type="info_paint_sprayer", x=160.0, y=528.0, z=-168.0, gel_item=blue_gel),
        GelData(object_name="paint_sprayer_jump_2", object_type="info_paint_sprayer", x=32.0, y=528.0, z=-168.0, gel_item=blue_gel),
        GelData(object_name="paint_sprayer_jump_2", object_type="info_paint_sprayer", x=-96.0, y=528.0, z=-168.0, gel_item=blue_gel),
        GelData(object_name="paint_sprayer_jump_2", object_type="info_paint_sprayer", x=-224.0, y=528.0, z=-168.0, gel_item=blue_gel),
        GelData(object_name="paint_sprayer_jump_2", object_type="info_paint_sprayer", x=-352.0, y=528.0, z=-168.0, gel_item=blue_gel),
        GelData(object_name="paint_sprayer_jump_2", object_type="info_paint_sprayer", x=160.0, y=688.0, z=-168.0, gel_item=blue_gel),
        GelData(object_name="paint_sprayer_jump_2", object_type="info_paint_sprayer", x=32.0, y=688.0, z=-168.0, gel_item=blue_gel),
        GelData(object_name="paint_sprayer_jump_2", object_type="info_paint_sprayer", x=-96.0, y=688.0, z=-168.0, gel_item=blue_gel),
        GelData(object_name="paint_sprayer_jump_2", object_type="info_paint_sprayer", x=-224.0, y=688.0, z=-168.0, gel_item=blue_gel),
        GelData(object_name="paint_sprayer_jump_2", object_type="info_paint_sprayer", x=-352.0, y=688.0, z=-168.0, gel_item=blue_gel),
        GelData(object_name="paint_sprayer_jump_2", object_type="info_paint_sprayer", x=-1632.0, y=1152.0, z=809.0, gel_item=blue_gel),
        GelData(object_name="paint_sprayer_jump_2", object_type="info_paint_sprayer", x=-1568.0, y=1024.0, z=809.0, gel_item=blue_gel),
        GelData(object_name="paint_sprayer_jump_2", object_type="info_paint_sprayer", x=-1632.0, y=960.0, z=809.0, gel_item=blue_gel),
        GelData(object_name="paint_sprayer_jump_2", object_type="info_paint_sprayer", x=-1560.0, y=896.0, z=809.0, gel_item=blue_gel),
        GelData(object_name="paint_sprayer_jump_2", object_type="info_paint_sprayer", x=-1696.0, y=896.0, z=809.0, gel_item=blue_gel),
        GelData(object_name="paint_sprayer_jump_2", object_type="info_paint_sprayer", x=-864.0, y=1088.0, z=1072.0, gel_item=blue_gel),
        GelData(object_name="paint_sprayer_jump_2", object_type="info_paint_sprayer", x=-832.0, y=1152.0, z=1072.0, gel_item=blue_gel),
        GelData(object_name="paint_sprayer_jump_2", object_type="info_paint_sprayer", x=-960.0, y=1328.0, z=1312.0, gel_item=blue_gel),
        GelData(object_name="paint_sprayer_jump_2", object_type="info_paint_sprayer", x=-832.0, y=1328.0, z=1312.0, gel_item=blue_gel),
        GelData(object_name="paint_sprayer_jump_2", object_type="info_paint_sprayer", x=-704.0, y=1328.0, z=1332.0, gel_item=blue_gel),
        GelData(object_name="paint_sprayer_jump_2", object_type="info_paint_sprayer", x=-576.0, y=1328.0, z=1280.0, gel_item=blue_gel),
        GelData(object_name="paint_sprayer_jump_2", object_type="info_paint_sprayer", x=-448.0, y=1328.0, z=1280.0, gel_item=blue_gel),
        GelData(object_name="paint_sprayer_jump_2", object_type="info_paint_sprayer", x=-320.0, y=1328.0, z=1312.0, gel_item=blue_gel),
        GelData(object_name="paint_sprayer_jump_2", object_type="info_paint_sprayer", x=-192.0, y=1328.0, z=1280.0, gel_item=blue_gel),
        GelData(object_name="paint_sprayer_jump_2", object_type="info_paint_sprayer", x=-232.0, y=976.0, z=1296.0, gel_item=blue_gel),
        GelData(object_name="paint_sprayer_jump_2", object_type="info_paint_sprayer", x=-320.0, y=976.0, z=1312.0, gel_item=blue_gel),
        GelData(object_name="paint_sprayer_jump_2", object_type="info_paint_sprayer", x=-448.0, y=976.0, z=1312.0, gel_item=blue_gel),
        GelData(object_name="paint_sprayer_jump_2", object_type="info_paint_sprayer", x=-576.0, y=976.0, z=1284.0, gel_item=blue_gel),
        GelData(object_name="paint_sprayer_jump_2", object_type="info_paint_sprayer", x=-704.0, y=976.0, z=1312.0, gel_item=blue_gel),
        GelData(object_name="paint_sprayer_jump_2", object_type="info_paint_sprayer", x=-832.0, y=976.0, z=1312.0, gel_item=blue_gel),
        GelData(object_name="paint_sprayer_jump_2", object_type="info_paint_sprayer", x=-960.0, y=976.0, z=1312.0, gel_item=blue_gel),
    ],
    "sp_a3_portal_intro": [
        GelData(object_name="pump_machine_white_sprayer", object_type="info_paint_sprayer", x=1908.0, y=1712.0, z=-1984.0, gel_item=white_gel),
        GelData(object_name="pump_machine_blue_sprayer", object_type="info_paint_sprayer", x=1088.0, y=1712.0, z=-2068.0, gel_item=blue_gel),
        GelData(object_name="intermediate_chamber_paint_sprayers", object_type="info_paint_sprayer", x=952.0, y=1272.0, z=-1672.0, gel_item=orange_gel),
        GelData(object_name="intermediate_chamber_paint_sprayers", object_type="info_paint_sprayer", x=1088.0, y=1280.0, z=-1672.0, gel_item=orange_gel),
        GelData(object_name="intermediate_chamber_paint_sprayers", object_type="info_paint_sprayer", x=1184.0, y=1264.0, z=-1672.0, gel_item=orange_gel),
        GelData(object_name="intermediate_chamber_paint_sprayers", object_type="info_paint_sprayer", x=1264.0, y=1277.0, z=-1672.0, gel_item=orange_gel),
        GelData(object_name="intermediate_chamber_paint_sprayers", object_type="info_paint_sprayer", x=1344.0, y=1266.0, z=-1672.0, gel_item=orange_gel),
        GelData(object_name="intermediate_chamber_paint_sprayers", object_type="info_paint_sprayer", x=1456.0, y=1283.0, z=-1672.0, gel_item=orange_gel),
        GelData(object_name="intermediate_chamber_paint_sprayers", object_type="info_paint_sprayer", x=1568.0, y=1280.0, z=-1672.0, gel_item=orange_gel),
        GelData(object_name="intermediate_chamber_paint_sprayers", object_type="info_paint_sprayer", x=1680.0, y=1282.0, z=-1672.0, gel_item=orange_gel),
        GelData(object_name="intermediate_chamber_paint_sprayers", object_type="info_paint_sprayer", x=1760.0, y=1296.0, z=-1672.0, gel_item=orange_gel),
        GelData(object_name="intermediate_chamber_paint_sprayers", object_type="info_paint_sprayer", x=1856.0, y=1287.0, z=-1672.0, gel_item=orange_gel),
        GelData(object_name="intermediate_chamber_paint_sprayers", object_type="info_paint_sprayer", x=1936.0, y=1296.0, z=-1672.0, gel_item=orange_gel),
        GelData(object_name="intermediate_chamber_paint_sprayers", object_type="info_paint_sprayer", x=2016.0, y=1277.0, z=-1672.0, gel_item=orange_gel),
        GelData(object_name="intermediate_chamber_paint_sprayers", object_type="info_paint_sprayer", x=1384.0, y=1244.0, z=-1728.0, gel_item=orange_gel),
        GelData(object_name="intermediate_chamber_paint_sprayers", object_type="info_paint_sprayer", x=1462.0, y=1240.0, z=-1704.0, gel_item=orange_gel),
        GelData(object_name="intermediate_chamber_paint_sprayers", object_type="info_paint_sprayer", x=1632.0, y=1244.0, z=-1712.0, gel_item=orange_gel),
        GelData(object_name="intermediate_chamber_paint_sprayers", object_type="info_paint_sprayer", x=1844.0, y=1248.0, z=-1680.0, gel_item=orange_gel),
        GelData(object_name="intermediate_chamber_paint_sprayers", object_type="info_paint_sprayer", x=1916.0, y=1244.0, z=-1712.0, gel_item=orange_gel),
        GelData(object_name="paint_sprayer_1", object_type="info_paint_sprayer", x=32.0, y=99.0, z=144.0, gel_item=white_gel),
        GelData(object_name="paint_sprayer_2", object_type="info_paint_sprayer", x=287.0, y=192.0, z=292.0, gel_item=white_gel),
    ],
    "sp_a3_speed_flings": [
        GelData(object_name="paint_sprayer_speed", object_type="info_paint_sprayer", x=2560.0, y=-128.0, z=-152.0, gel_item=orange_gel),
        GelData(object_name="paint_sprayer_bounce", object_type="info_paint_sprayer", x=2816.0, y=-128.0, z=320.0, gel_item=blue_gel),
    ],
    "sp_a3_speed_ramp": [
        GelData(object_name="paint_sprayer", object_type="info_paint_sprayer", x=576.0, y=0.0, z=704.0, gel_item=orange_gel),
        GelData(object_name="paint_sprayer", object_type="info_paint_sprayer", x=576.0, y=0.0, z=696.0, gel_item=orange_gel),
        GelData(object_name="paint_sprayer_2", object_type="info_paint_sprayer", x=-1600.0, y=-896.0, z=960.0, gel_item=orange_gel),
        GelData(object_name="paint_sprayer_3", object_type="info_paint_sprayer", x=-1600.0, y=-384.0, z=960.0, gel_item=blue_gel),
    ],
    "sp_a4_finale1": [
        GelData(object_name="paint_bomb_maker", object_type="point_template", x=-9936.0, y=-2208.0, z=794.0, gel_item=white_gel),
        GelData(object_name="paint_bomb", object_type="prop_paint_bomb", x=-9936.0, y=-2208.0, z=826.0, gel_item=white_gel),
        GelData(object_name="platform_sprayer", object_type="info_paint_sprayer", x=-8881.0, y=-2038.0, z=-214.0, gel_item=white_gel),
        GelData(object_name="paint_sprayer_portal", object_type="info_paint_sprayer", x=-8928.0, y=-2016.0, z=-239.0, gel_item=white_gel),
        GelData(object_name="paint_sprayer_portal", object_type="info_paint_sprayer", x=-8944.0, y=-2048.0, z=-239.0, gel_item=white_gel),
        GelData(object_name="paint_sprayer_portal", object_type="info_paint_sprayer", x=-8928.0, y=-2080.0, z=-239.0, gel_item=white_gel),
        GelData(object_name="paint_sprayer_portal", object_type="info_paint_sprayer", x=-8896.0, y=-2096.0, z=-239.0, gel_item=white_gel),
        GelData(object_name="paint_sprayer_portal", object_type="info_paint_sprayer", x=-8896.0, y=-2000.0, z=-239.0, gel_item=white_gel),
        GelData(object_name="paint_sprayer_portal", object_type="info_paint_sprayer", x=-8896.0, y=-2048.0, z=-239.0, gel_item=white_gel),
        GelData(object_name="paint_sprayer_portal", object_type="info_paint_sprayer", x=-8864.0, y=-2016.0, z=-239.0, gel_item=white_gel),
        GelData(object_name="paint_sprayer_portal", object_type="info_paint_sprayer", x=-8848.0, y=-2048.0, z=-239.0, gel_item=white_gel),
        GelData(object_name="paint_sprayer_portal", object_type="info_paint_sprayer", x=-8864.0, y=-2080.0, z=-239.0, gel_item=white_gel),
    ],
    "sp_a4_finale2": [
        GelData(object_name="paint_sprayer_jump", object_type="info_paint_sprayer", x=-1710.0, y=-1226.0, z=-503.0, gel_item=blue_gel),
        GelData(object_name="paint_sprayer_jump", object_type="info_paint_sprayer", x=-1710.0, y=-1202.0, z=-503.0, gel_item=blue_gel),
        GelData(object_name="paint_trickle_blue", object_type="info_paint_sprayer", x=-1648.0, y=-1200.0, z=168.0, gel_item=blue_gel),
        GelData(object_name="sprayer_broken_pipe", object_type="info_paint_sprayer", x=-1888.0, y=-1632.0, z=-455.0, gel_item=blue_gel),
        GelData(object_name="sprayer_broken_pipe", object_type="info_paint_sprayer", x=-1844.0, y=-1612.0, z=-455.0, gel_item=blue_gel),
        GelData(object_name="sprayer_broken_pipe", object_type="info_paint_sprayer", x=-1832.0, y=-1580.0, z=-455.0, gel_item=blue_gel),
        GelData(object_name="sprayer_broken_pipe", object_type="info_paint_sprayer", x=-1832.0, y=-1504.0, z=-443.0, gel_item=blue_gel),
        GelData(object_name="sprayer_broken_pipe", object_type="info_paint_sprayer", x=-1888.0, y=-1504.0, z=-443.0, gel_item=blue_gel),
        GelData(object_name="bomb", object_type="prop_paint_bomb", x=-1440.0, y=-608.0, z=-497.0, gel_item=blue_gel),
        GelData(object_name="trigger_to_drop", object_type="logic_relay", x=-1432.0, y=-608.0, z=-295.0, gel_item=blue_gel),
        GelData(object_name="template_artillery_paint_bomb", object_type="point_template", x=-1440.0, y=-608.0, z=-119.0, gel_item=blue_gel),
        GelData(object_name="artillery_paint_bomb", object_type="prop_paint_bomb", x=-1440.0, y=-608.0, z=-87.0, gel_item=blue_gel),
    ],
    "sp_a4_finale3": [
        GelData(object_name="practice_paint_sprayer", object_type="info_paint_sprayer", x=-128.0, y=-2872.0, z=288.0, gel_item=white_gel),
        GelData(object_name="paint_sprayer_break", object_type="info_paint_sprayer", x=-960.0, y=27.0, z=-111.0, gel_item=orange_gel),
        GelData(object_name="paint_sprayer_break", object_type="info_paint_sprayer", x=-985.0, y=61.0, z=-105.0, gel_item=orange_gel),
        GelData(object_name="paint_sprayer", object_type="info_paint_sprayer", x=-960.0, y=-56.0, z=-223.0, gel_item=orange_gel),
        GelData(object_name="paint_sprayer_2", object_type="info_paint_sprayer", x=-960.0, y=113.0, z=-70.0, gel_item=orange_gel),
    ],
    "sp_a4_finale4": [
        GelData(object_name="toxin_paint_sprayer", object_type="info_paint_sprayer", x=882.0, y=256.0, z=192.0, gel_item=white_gel),
        GelData(object_name="panel1_paint_sprayer", object_type="info_paint_sprayer", x=754.0, y=240.0, z=160.0, gel_item=white_gel),
        GelData(object_name="panel2_paint_sprayer", object_type="info_paint_sprayer", x=754.0, y=240.0, z=160.0, gel_item=white_gel),
        GelData(object_name="panel3_paint_sprayer", object_type="info_paint_sprayer", x=754.0, y=256.0, z=160.0, gel_item=white_gel),
        GelData(object_name="panel4_paint_sprayer", object_type="info_paint_sprayer", x=754.0, y=256.0, z=160.0, gel_item=white_gel),
        GelData(object_name="panel5_paint_sprayer", object_type="info_paint_sprayer", x=754.0, y=256.0, z=160.0, gel_item=white_gel),
        GelData(object_name="panel6_paint_sprayer", object_type="info_paint_sprayer", x=754.0, y=256.0, z=160.0, gel_item=white_gel),
        GelData(object_name="panel7_paint_sprayer", object_type="info_paint_sprayer", x=722.0, y=256.0, z=160.0, gel_item=white_gel),
        GelData(object_name="paint_white_event_sphere1", object_type="paint_sphere", x=560.0, y=256.0, z=16.0, gel_item=white_gel),
        GelData(object_name="paint_white_event_sphere2", object_type="paint_sphere", x=288.0, y=256.0, z=16.0, gel_item=white_gel),
        GelData(object_name="paint_white_event_sphere3", object_type="paint_sphere", x=448.0, y=64.0, z=64.0, gel_item=white_gel),
        GelData(object_name="paint_white_event_sphere4", object_type="paint_sphere", x=432.0, y=528.0, z=16.0, gel_item=white_gel),
        GelData(object_name="paint_white_event_sphere5", object_type="paint_sphere", x=544.0, y=-160.0, z=16.0, gel_item=white_gel),
        GelData(object_name="paint_white_event_sphere6", object_type="paint_sphere", x=240.0, y=0.0, z=64.0, gel_item=white_gel),
        GelData(object_name="paint_white_event_sphere7", object_type="paint_sphere", x=384.0, y=800.0, z=16.0, gel_item=white_gel),
        GelData(object_name="paint_white_event_sphere8", object_type="paint_sphere", x=144.0, y=480.0, z=16.0, gel_item=white_gel),
        GelData(object_name="paint_white_event_sphere9", object_type="paint_sphere", x=0.0, y=256.0, z=8.0, gel_item=white_gel),
        GelData(object_name="paint_white_event_sphere10", object_type="paint_sphere", x=128.0, y=800.0, z=16.0, gel_item=white_gel),
        GelData(object_name="wall_panel1-paint_portal_sprayer", object_type="paint_sphere", x=0.0, y=-325.0, z=578.0, gel_item=white_gel),
        GelData(object_name="wall_panel2-paint_portal_sprayer", object_type="paint_sphere", x=0.0, y=-403.0, z=443.0, gel_item=white_gel),
        GelData(object_name="wall_panel3-paint_portal_sprayer", object_type="paint_sphere", x=-290.0, y=-247.0, z=578.0, gel_item=white_gel), # Wrong on SS
        GelData(object_name="wall_panel11-paint_portal_sprayer", object_type="paint_sphere", x=-346.0, y=775.0, z=578.0, gel_item=white_gel),
        GelData(object_name="wall_panel16-paint_portal_sprayer", object_type="paint_sphere", x=329.0, y=827.0, z=443.0, gel_item=white_gel),
        GelData(object_name="wall_panel17-paint_portal_sprayer", object_type="paint_sphere", x=503.0, y=546.0, z=578.0, gel_item=white_gel),
        GelData(object_name="wall_panel24-paint_portal_sprayer", object_type="paint_sphere", x=329.0, y=-315.0, z=443.0, gel_item=white_gel),
        GelData(object_name="wall_panel26-paint_portal_sprayer", object_type="paint_sphere", x=728.0, y=-368.0, z=60.0, gel_item=white_gel),
        GelData(object_name="paint_blue_event_sphere1", object_type="paint_sphere", x=-544.0, y=96.0, z=32.0, gel_item=blue_gel),
        GelData(object_name="paint_blue_event_sphere2", object_type="paint_sphere", x=-544.0, y=288.0, z=32.0, gel_item=blue_gel),
        GelData(object_name="paint_blue_event_sphere3", object_type="paint_sphere", x=-544.0, y=448.0, z=32.0, gel_item=blue_gel), # Wrong on SS
        GelData(object_name="paint_blue_event_sphere4", object_type="paint_sphere", x=-288.0, y=192.0, z=32.0, gel_item=blue_gel),
        GelData(object_name="paint_blue_event_sphere5", object_type="paint_sphere", x=240.0, y=144.0, z=24.0, gel_item=blue_gel),
        GelData(object_name="paint_blue_sprayer", object_type="info_paint_sprayer", x=-544.0, y=-16.0, z=320.0, gel_item=blue_gel),
        
        # Cannot removed last 2 blobs from finale4 at the moment
        GelData(object_name="pipe_bounce_paint_bomb_template1", object_type="point_template", x=-576.0, y=256.0, z=320.0, gel_item=blue_gel), # Doesn't work
        # Above handles these two
        # GelData(object_name="pipe_bounce_paint_bomb1", object_type="prop_paint_bomb", x=-544.0, y=256.0, z=352.0, gel_item=blue_gel),
        # GelData(object_name="pipe_bounce_paint_bomb1", object_type="prop_paint_bomb", x=-544.0, y=256.0, z=288.0, gel_item=blue_gel),
        GelData(object_name="paint_speed_sprayer", object_type="info_paint_sprayer", x=752.0, y=-368.0, z=184.0, gel_item=orange_gel),
        GelData(object_name="paint_orange_sphere", object_type="paint_sphere", x=544.0, y=-360.0, z=32.0, gel_item=orange_gel),
        GelData(object_name="paint_speed_bomb_maker", object_type="point_template", x=616.0, y=-368.0, z=336.0, gel_item=orange_gel), # Doesn't work
        # Above handles this one
        # GelData(object_name="paint_speed_bomb", object_type="prop_paint_bomb", x=616.0, y=-368.0, z=368.0, gel_item=orange_gel),
        
        GelData(object_name="paint_white_ending_sphere", object_type="paint_sphere", x=0.0, y=256.0, z=8.0, gel_item=white_gel),
    ],
    "sp_a4_jump_polarity": [
        GelData(object_name="antechamber-paint_meSilly", object_type="info_paint_sprayer", x=1742.0, y=-62.0, z=140.0, gel_item=white_gel),
        GelData(object_name="antechamber-paint_meSilly", object_type="info_paint_sprayer", x=1902.0, y=65.0, z=188.0, gel_item=white_gel),
        GelData(object_name="paint_sprayer", object_type="info_paint_sprayer", x=-576.0, y=-64.0, z=640.0, gel_item=blue_gel),
    ],
    "sp_a4_speed_tb_catch": [
        GelData(object_name="AutoInstance1-paint_sprayer", object_type="info_paint_sprayer", x=256.0, y=1376.0, z=552.0, gel_item=orange_gel),
    ],
}
